### ISSUE TITLE
PDF Print with error

### ISSUE THREAD

**Issue by hitzi** [hholzgra/ocitysmap#13]
[014357_2018-03-05_23-32_test-annweiler.pdf](https://github.com/hholzgra/ocitysmap/files/1782883/014357_2018-03-05_23-32_test-annweiler.pdf) from map task: https://maposmatic.osm-baustelle.de/maps/14357
The attached map is only printable on page 1 and 2 sometimes only the front page.  The printer show an error like:
Error: undefined
OFFENDING COMMAND: clipsave
STACK: 

- 
I checked different laser printers. Viewing with Adobe Acrobat Reader DC Version 2018.011.20038 is without problems, but printing.
Used Version of cairo on maposmatic.osm-baustelle.de is cairo 1.14.8
My Version on my ocitysmap instance is also 1.14.8.

**Comment by hholzgra** [comment]
PDF file prints fine here, tested with:

* GNOME Document Viewer 3.18.2 (evince)
* Acrobat Reader 9.5.5  04/26/2013  

on Ubuntu 16.04 with a Brother HL-4150CDN color laser attached via network

Can't test any more recent version of Acrobat Reader as Adobe stopped supporting Linux after 9.5.5

**Comment by hitzi** [comment]
On one test I used the same printer but with win7/adobe. I will try evince on linux and digging for more information.

**Comment by hholzgra** [comment]
Can you test with win7/adobe once more, with a newly generated map? I might already have fixed this recently, but can't test myself ...

**Comment by hitzi** [comment]
Win7 is difficult, because eol. maybe i have some vm or something else....I will try to test.

**Comment by hholzgra** [comment]
As no similar problems have been reported over the last years I assume that this was already fixed indeed
