### ISSUE TITLE
Rewrite stylelib/Umap.py to use jq for Umap json parsing

### ISSUE THREAD

**Issue by hholzgra** [hholzgra/ocitysmap#34]
The current parsing code is ugly, and there may be more problems like 

https://github.com/hholzgra/maposmatic/issues/58

still hidden in it.

Rewriting the Umap json -> geojson conversion code to extract features using jq instead of raw python code should make things much more readable, and so maintainable.

**Comment by claude1000** [comment]
thanks

**Comment by hholzgra** [comment]
I'm not really happy with

https://github.com/mwilliamson/jq.py

as you can compile the search expressions, but JSON must be passed in as string input, and so parsed every time again and again.

**Comment by hholzgra** [comment]
closing, see also #65
