### ISSUE TITLE
Downloading SVGZ results in error

### ISSUE THREAD

**Issue by vitrinekast** [hholzgra/ocitysmap#36]
When downloading a map in SVGZ, in my case [https://print.get-map.org/maps/208909](https://print.get-map.org/maps/208909), I get the following error:

```
This page contains the following errors:
error on line 1 at column 1: Encoding error
Below is a rendering of the page up to the first error.
```

**Comment by hholzgra** [comment]
The file is delivered correctly as gzip compressed SVG, but the content header is generated as 

`
  Content-Type: image/svg+xml
`

but seems to be missing

`
Content-Encoding: gzip
`

so browsers that try to display the SVG directly stumble ... it is still possible to do "Save as ..." to save the received file.

Need to play with this a bit to see if adding gzip content encoding is sufficient, or may lead to other problems ...

**Comment by hholzgra** [comment]
See also https://github.com/w3c/svgwg/issues/701

**Comment by hholzgra** [comment]
Fixed by https://github.com/hholzgra/maposmatic/commit/1520059c7d6cf4c0dd62a8019cfcd16e330a8732
