### ISSUE TITLE
UTM zone clipping does not work correctly

### ISSUE THREAD

**Issue by hartmut-mariadb** [hholzgra/ocitysmap#84]
They way the grid rendering function works clipping rectangles are used that should prevent grid lines from overlapping across zone boundaries.

For some strange reason this does not really work though, even though the right edge of the left zones grid clipping area has the same X coordinate as the left edge of the right zone there's an overlap of ca. 62 pixels somehow ...

![clipping-problem](https://user-images.githubusercontent.com/50832275/213888041-7bec5904-f6c4-40e7-af9e-1c094917923a.png)

**Comment by hholzgra** [comment]
Now this was pretty stupid after all, the parameters of the Cairo rectangle function are not (x1,y1,x2,y2) coordinates for top left and bottom right corner, but (x,y,width,height)

So a simple one liner change fixed this

**Comment by hartmut-mariadb** [comment]
![good-grid](https://user-images.githubusercontent.com/50832275/213913182-11324f67-48ed-47fb-8b5b-88bf0976a56a.png)
